name: lab_212287
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.0.0
  sizer: ^2.0.15
  intl: ^0.19.0
  flutter_linkify: ^6.0.0
  url_launcher: ^6.2.6
  country_flags: ^2.2.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

